### ISSUE TITLE
tests fail when run outside a git repo

### ISSUE THREAD

**Issue by pravi** [benbalter/licensee#101]
tests fail when run outside a git repo. I'm packaging licensee for debian (dependency for gitlab).

```
Finished in 2.124265s, 105.4482 runs/s, 168.5289 assertions/s.

  1) Error:
TestLicenseeGemspecMatchers#test_: LicenseeGemspecMatchers should detect its own license. :
Licensee::GitProject::InvalidRepository: Licensee::GitProject::InvalidRepository
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:20:in `rescue in initialize'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:11:in `initialize'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/test/test_licensee_gemspec_matcher.rb:6:in `new'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/test/test_licensee_gemspec_matcher.rb:6:in `block in <class:TestLicenseeGemspecMatchers>'
    /usr/lib/ruby/vendor_ruby/shoulda/context/context.rb:413:in `instance_exec'
    /usr/lib/ruby/vendor_ruby/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:108:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:205:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:105:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:256:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:104:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:276:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:103:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:778:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:305:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:293:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:318:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:291:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:129:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:56:in `block in autorun'


  2) Failure:
TestLicenseeBin#test_: LicenseeBin should work via commandline.  [/home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/test/test_licensee_bin.rb:10]:
expected  to include `License: MIT`


  3) Error:
packages#test_: packages should detect a package file. :
Licensee::GitProject::InvalidRepository: Licensee::GitProject::InvalidRepository
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:20:in `rescue in initialize'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:11:in `initialize'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/test/test_licensee_project.rb:83:in `new'
    /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/test/test_licensee_project.rb:83:in `block (2 levels) in <class:TestLicenseeProject>'
    /usr/lib/ruby/vendor_ruby/shoulda/context/context.rb:413:in `instance_exec'
    /usr/lib/ruby/vendor_ruby/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:108:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:205:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:105:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:256:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:104:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:276:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:103:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:778:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:305:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:293:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:318:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:291:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:129:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:56:in `block in autorun'

224 runs, 358 assertions, 1 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"test" -I"/usr/lib/ruby/vendor_ruby" "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/test_licensee.rb" "test/test_licensee_bin.rb" "test/test_licensee_copyright_matcher.rb" "test/test_licensee_dice_matcher.rb" "test/test_licensee_exact_matcher.rb" "test/test_licensee_gemspec_matcher.rb" "test/test_licensee_license.rb" "test/test_licensee_license_file.rb" "test/test_licensee_npm_bower_matcher.rb" "test/test_licensee_package_info.rb" "test/test_licensee_project.rb" "test/test_licensee_project_file.rb" "test/test_licensee_readme.rb" "test/test_licensee_vendor.rb" -v]
```

**Comment by pravi** [comment]
I extract the gem file into a directory and run tests from there, so git commands will not work. At the least these tests should be skipped if git repo is not detected.

**Comment by pravi** [comment]
```
$ ./bin/licensee 
/home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:20:in `rescue in initialize': Licensee::GitProject::InvalidRepository (Licensee::GitProject::InvalidRepository)
	from /home/pravi/forge/debian/gitlab/ruby-licensee-8.0.0/lib/licensee/projects/git_project.rb:11:in `initialize'
	from ./bin/licensee:7:in `new'
	from ./bin/licensee:7:in `<main>'
```

**Comment by benbalter** [comment]
@pravi what would you recommend we do in this instance? We *want* to test the Git functionality as it's a core part of the Gem's detection.

**Comment by pravi** [comment]
@benbalter I have skipped these tests in debian package. May be you can check if the tests are run from a git repo and skip if not found to be a git repo.
