### ISSUE TITLE
Exception if license file contains UTF-8 characters

### ISSUE THREAD

**Issue by huerlisi** [benbalter/licensee#27]
The checker raises an exception if a file contains UTF-8 characters, possibly in the copyright notice.

While I can handle that quite easy by transliterating to Huerlimann, it feels like the '90s and is not possible for all copyright holders as easily.

```
shuerlimann@tom:~/src/i18n_rails_helpers$ file MIT-LICENSE 
MIT-LICENSE: UTF-8 Unicode text
shuerlimann@tom:~/src/i18n_rails_helpers$ head -5 MIT-LICENSE 
Copyright (c) 2010-2014 Simon Hürlimann <simon.huerlimann@cyt.ch>
Copyright (c) 2010-2014 CyT <http://www.cyt.ch>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
shuerlimann@tom:~/src/i18n_rails_helpers$ licensee 
License file: MIT-LICENSE
/home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/matchers/copyright_matcher.rb:7:in `=~': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/matchers/copyright_matcher.rb:7:in `match'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/license_file.rb:38:in `block in matcher'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/license_file.rb:38:in `each'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/license_file.rb:38:in `find'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/license_file.rb:38:in `matcher'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/lib/licensee/license_file.rb:43:in `match'
        from /home/shuerlimann/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/licensee-4.4.0/bin/licensee:9:in `<top (required)>'
        from /home/shuerlimann/.rbenv/versions/2.1.5/bin/licensee:23:in `load'
        from /home/shuerlimann/.rbenv/versions/2.1.5/bin/licensee:23:in `<main>'
```

**Comment by stapelberg** [comment]
I also just ran into that with a file containing the ⓒ glyph.
