### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#71]
Running on: https://github.com/awslabs/java-meme-generator-sample

Gives:

$ licensee
License file: LICENSE.txt
/Library/Ruby/Gems/2.0.0/gems/licensee-6.0.0/lib/licensee/project_file.rb:44:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/licensee-6.0.0/lib/licensee/project_file.rb:44:in `attribution'
	from /Library/Ruby/Gems/2.0.0/gems/licensee-6.0.0/bin/licensee:11:in `<top (required)>'
	from /usr/bin/licensee:23:in `load'
	from /usr/bin/licensee:23:in `<main>'

Agreed that the LICENSE.txt file shouldn't have MS Word (I'm guessing) characters in, but before I fix that I thought I'd share the bug with you.

**Comment by hyandell** [comment]
Confirming the guess, it's from 0x91 to 0x94 being used in MS Word documents (slanted single and double quotes).

Solutions that jump to mind:

1) catch the ArgumentError higher in the code (either as a warning from licensee or by the user if used as a library), which will drive a behaviour of fixing the files.
2) content_helper could silently replace 0x91/0x92 with ' and 0x93/0x94 with " on every line. 
3) Recognize encoding of file etc. Not highly exciting :)
